### ISSUE TITLE
DomainReloading support?

### ISSUE THREAD

**Issue by AndrewNovakP** [KyryloKuzyk/PrimeTween#1]
Hi there. 

Nice asset. I can see you use Statics. Can he support [DomainReloading](https://docs.unity3d.com/Manual/DomainReloading.html)?

**Comment by KyryloKuzyk** [comment]
Of course! I use the disabled 'Reload Domain setting' all the time and PrimeTween is built with this setting in mind.

PrimeTween even works fine with the 'Recompile And Continue Playing' setting: if you re-compile your project on the fly, PrimeTween will stop all running tweens and will continue to work fine like nothing has happened.
