### ISSUE TITLE
Demo classes should be in namespace

### ISSUE THREAD

**Issue by mmatinaho-dodreams** [KyryloKuzyk/PrimeTween#12]
Demo classes should be in namespace, maybe PrimeTween.Demo or something.
If importing to existing Project, demo has classes that are using common names such as "Demo" and "Door" as class names and its prone to cause conflicts if project already contains them in global namespace. Many developers want to easily evaluate the project even if they will delete the demo assets afterwards.

**Comment by KyryloKuzyk** [comment]
Good point!
Will address this in the upcoming version.

**Comment by KyryloKuzyk** [comment]
Fixed in version 1.0.11.
