### ISSUE TITLE
Errors with UI.Sliders

### ISSUE THREAD

**Issue by dadropa** [KyryloKuzyk/PrimeTween#120]
It's weird, but when I try to use Tween.ShakeLocalRotation on Slider.transform, I see an error every time
![2024-10-23_14-10-28](https://github.com/user-attachments/assets/82456fb0-1f13-4432-8a73-cc138669b566)
I know for sure that there is a reference of the Slider, and moreover, some parts of the code work, and some do not
![2024-10-23_14-14-51](https://github.com/user-attachments/assets/d0202938-11f5-4e28-bd44-9c125e89ae8e)
What's more interesting, this Tween is triggered even before the condition becomes true

**Comment by mwp007** [comment]
What was the problem?

**Comment by KyryloKuzyk** [comment]
Hey! The unity’s error is correct in that the StressSlider has been destroyed. 

Why there is an exception at line 81 but not at 77? My assumption is that the 'value' property doesn't have the object destruction check while the 'transform' has.
