### ISSUE TITLE
MissingReferenceException after LoadScene

### ISSUE THREAD

**Issue by dadropa** [KyryloKuzyk/PrimeTween#121]
When running from the editor, everything works correctly. at one point, SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex) is triggered, and this error is appear.
![2024-10-23_23-00-33](https://github.com/user-attachments/assets/70a58a3f-83cf-4bf2-849e-d892b67e3435)
86 line
![2024-10-23_23-09-56](https://github.com/user-attachments/assets/1fd4075c-3c47-4395-b11d-2ffe5ddabea7)
I tried to use DontDestroyOnLoad, but it didn't help
Also, objects are never deleted as the game progresses, so I don't understand what the problem is.

**Comment by KyryloKuzyk** [comment]
Hey! When you load a new scene, Unity destroys all objects in the current scene, then loads the new scene. 

Please check that you don't call the GetColliderHit() on the destroyed object. 

Closing this issue because this error comes from Unity and not related to PrimeTween itself.
