### ISSUE TITLE
Getting nondeterministic behavior / race conditions when awaiting Sequences

### ISSUE THREAD

**Issue by ahSOLO** [KyryloKuzyk/PrimeTween#123]
The following code does not always await properly, about 60% of the time the Sequence is set to "dead" immediately after awaiting and ignored entirely. I confirmed that the Tweens and durations were being added correctly.

```
    private async UniTask FadeOutStoryTextAsync()
    {
        List<GameObject> storyTextGos = new(storyParent.childCount);
        var tweenSeq = Sequence.Create();
        foreach (Transform go in storyParent.transform)
        {
            storyTextGos.Add(go.gameObject);
            var cG = go.GetComponent<CanvasGroup>();
            if (cG.alpha != 0f)
            {
                tweenSeq.Group(Tween.Alpha(cG, endValue: 0f, duration: 30f, ease: Ease.InOutCubic));
            }
        }
        await tweenSeq; // This doesn't await properly

        for (int i = storyTextGos.Count - 1; i >= 0; i--)
        {
            Destroy(storyTextGos[i].gameObject);
        }
        _cgsToAnimate.Clear();
        scrollRect.verticalNormalizedPosition = 0;
    }
```

![image](https://github.com/user-attachments/assets/10df4874-c939-4814-be42-939bb1844f5f)
![image](https://github.com/user-attachments/assets/695affe1-5a09-478c-b88f-57293fd759bd)

Changing the Sequence to a collection of UniTask resolves the problem, and the tweens run as expected 100% of the time.

```
    private async UniTask FadeOutStoryTextAsync()
    {
        List<GameObject> storyTextGos = new(storyParent.childCount);
        List<UniTask> tweenTasks = new (); // A sequence doesn't work here for some reason
        foreach (Transform go in storyParent.transform)
        {
            storyTextGos.Add(go.gameObject);
            var cG = go.GetComponent<CanvasGroup>();
            if (cG.alpha != 0f)
            {
                tweenTasks.Add(Tween.Alpha(cG, endValue: 0f, duration: 3f, ease: Ease.InOutCubic).ToYieldInstruction().ToUniTask());
            }
        }
        await UniTask.WhenAll(tweenTasks);

        for (int i = storyTextGos.Count - 1; i >= 0; i--)
        {
            Destroy(storyTextGos[i].gameObject);
        }
        _cgsToAnimate.Clear();
        scrollRect.verticalNormalizedPosition = 0;
    }
    ```

**Comment by KyryloKuzyk** [comment]
Hey Andrew, thank you for the bug report!

Unfortunately, I wasn't able to reproduce the issue on my end. I tried both with and without Unitask to check for all cases.
The only case I can come up with when an 'await' can be ignored is when one of the tween targets is destroyed while the sequence is running. Is there a chance you destroy storyParent of any of its children while awaiting the sequence?

Also, would it be possible for you to create a simple reproducible example in isolation from your current project? That would help me tremendously in finding and fixing a potential issue.

**Comment by ahSOLO** [comment]
Thanks so much for the reply! Yes it turned out I was calling Destroy on an object immediately before running the sequence, so depending on how long the entire delayed the Destroy call it would affect whether the object was included in the Tween. Adding a frame long delay before starting the Sequence resolved the issue. Thanks again!
