### ISSUE TITLE
Is it possible to add methods that can run in the Unity editor?

### ISSUE THREAD

**Issue by o2co2** [KyryloKuzyk/PrimeTween#17]
Is it possible to add methods that can run in the Unity editor?

**Comment by KyryloKuzyk** [comment]
Do you mean running tweens in the Edit mode, while a scene is not playing? Unfortunately, no, currently PrimeTween only works in runtime. I have the Edit mode feature on my roadmap, although I can't give any precise estimates right now.

**Comment by o2co2** [comment]
Thank you for your reply and hope to use it someday

**Comment by coty-crg** [comment]
+1 I'd also appreciate this feature. We were using it in DoTween for our in-unity level editor. Not a huge loss, but it's a very comfy feature to have for our level designers.
