### ISSUE TITLE
How stop (destroy) all tweens in scene?

### ISSUE THREAD

**Issue by ShockWave2048** [KyryloKuzyk/PrimeTween#18]
Hi Kyrylo!
How stop (destroy) all tweens in scene?
Thanks!

**Comment by KyryloKuzyk** [comment]
If you have one only one scene loaded, you can stop all tweens by calling `Tween.StopAll()`. If you have multiple scenes loaded, there is currently no way to stop all tweens only in one specific scene.
I should mention that with PrimeTween it's safe to [change scenes or destroy objects](https://github.com/KyryloKuzyk/PrimeTween/discussions/4) with running tweens, so using `Tween.StopAll()` may not be even necessary in the majority of cases.
