### ISSUE TITLE
The name 'Assert' does not exist in the current context

### ISSUE THREAD

**Issue by BudaCoca** [KyryloKuzyk/PrimeTween#22]
Unity 2022.3.12f1 on Windows

Assets\Plugins\PrimeTween\Demo\Scripts\MeasureAllocations\MeasureMemoryAllocations.cs(64,21): error CS0103: The name 'Assert' does not exist in the current context

Adding "using UnityEngine.Assertions;" solves it. Installing PrimeTween also solves it.

**Comment by KyryloKuzyk** [comment]
Huge thanks for reporting the bug!
I uploaded a new version 1.0.17 with a fix.
