### ISSUE TITLE
SetCycles then StopAll cause AssertFail

### ISSUE THREAD

**Issue by networm** [KyryloKuzyk/PrimeTween#23]
# PrimeTween 1.0.17

## Update

- 2023-11-21

## Environment

- Unity 2019.4.32f1
- PrimeTween 1.0.17

## Reproduce steps

1. Open project
2. Open Test1.unity
3. Play

## Error

```log
AssertionException: Assertion failure. Values are not equal.
Expected: 0 == 1
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <781ae7ac455e4981a7a57fe4b3a3ae5b>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <781ae7ac455e4981a7a57fe4b3a3ae5b>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message) (at <781ae7ac455e4981a7a57fe4b3a3ae5b>:0)
PrimeTween.Assert.AreEqual[T] (T expected, T actual, System.String msg) (at Library/PackageCache/com.kyrylokuzyk.primetween@2728f0d0794b-1699791494000/Runtime/Internal/Assert.cs:7)
PrimeTween.ReusableTween.rewindIncrementalTween () (at Library/PackageCache/com.kyrylokuzyk.primetween@2728f0d0794b-1699791494000/Runtime/Internal/ReusableTween.cs:155)
PrimeTween.Sequence.restart_internal () (at Library/PackageCache/com.kyrylokuzyk.primetween@2728f0d0794b-1699791494000/Runtime/Sequence.cs:395)
PrimeTween.Sequence.restart () (at Library/PackageCache/com.kyrylokuzyk.primetween@2728f0d0794b-1699791494000/Runtime/Sequence.cs:376)
PrimeTween.Sequence.onTweenKilled (System.Int32 tweenId) (at Library/PackageCache/com.kyrylokuzyk.primetween@2728f0d0794b-1699791494000/Runtime/Sequence.cs:235)
PrimeTween.ReusableTween.updateSequenceAfterKill () (at Library/PackageCache/com.kyrylokuzyk.primetween@2728f0d0794b-1699791494000/Runtime/Internal/ReusableTween.cs:401)
PrimeTween.Tween+<>c.<StopAll>b__838_0 (PrimeTween.ReusableTween tween) (at Library/PackageCache/com.kyrylokuzyk.primetween@2728f0d0794b-1699791494000/Runtime/TweenMethods.cs:30)
PrimeTween.PrimeTweenManager.processAll_internal (System.Object onTarget, System.Predicate`1[T] predicate, System.Nullable`1[T] minExpected, System.Nullable`1[T] numMaxExpected) (at Library/PackageCache/com.kyrylokuzyk.primetween@2728f0d0794b-1699791494000/Runtime/Internal/PrimeTweenManager.cs:379)
PrimeTween.PrimeTweenManager.processAll (System.Object onTarget, System.Predicate`1[T] predicate, System.Nullable`1[T] numMinExpected, System.Nullable`1[T] numMaxExpected) (at Library/PackageCache/com.kyrylokuzyk.primetween@2728f0d0794b-1699791494000/Runtime/Internal/PrimeTweenManager.cs:367)
PrimeTween.Tween.StopAll (System.Object onTarget, System.Nullable`1[T] numMinExpected, System.Nullable`1[T] numMaxExpected) (at Library/PackageCache/com.kyrylokuzyk.primetween@2728f0d0794b-1699791494000/Runtime/TweenMethods.cs:28)
Test1.Update () (at Assets/Test1.cs:20)
```

## Key

`SetCycles()` is the key line. If you don't set it at all, then all things works perfectly.

## Repository

* [networm/TestPrimeTween1.0.17](https://github.com/networm/TestPrimeTween1.0.17)

**Comment by networm** [comment]
Just run this script

```csharp
﻿using PrimeTween;
using UnityEngine;

public class Test1 : MonoBehaviour
{
    private int _frame;

    void Start()
    {
        var seq = Sequence.Create();
        seq.Group(Tween.LocalPositionX(transform, 0.6f, 0.1f));
        seq.SetCycles(10);
    }

    void Update()
    {
        _frame++;
        if (_frame == 120)
        {
            Tween.StopAll(transform);
        }
    }
}
```

**Comment by KyryloKuzyk** [comment]
Huge thanks for the perfect bug report! Will look at it asap.

**Comment by networm** [comment]
Reproduced on Unity 2022.3.0f1

**Comment by KyryloKuzyk** [comment]
I can confirm the issue exists, thanks again for the high-quality bug report!

While I can make sure such a scenario doesn't produce any errors, I believe the proper fix should go much deeper than that. I was thinking about it a lot, and I believe that stopping a particular tween inside a Sequence should not be allowed at all.

In this particular case, when a Sequence has one tween with one 'transform' target, it's reasonable to assume that `Tween.StopAll(transform)` should stop the whole sequence. But what is the expected result if the sequence has tweens with multiple other targets? Currently, the sequence will continue running while it has at least one 'alive' tween, but I think this behavior is very hard to understand and very hard to reason about in a real project.

So I think the proper solution would be to not allow stopping the tween inside a Sequence at all. It's much simpler to reason about a Sequence as a group of tweens, that should be manipulated as a whole.

As an alternative solution for your use case, I can introduce a new API `Sequence.Create(object sequenceTarget)`, so it's then possible to stop the whole sequence with Tween.StopAll(sequenceTarget). What do you think?

**Comment by networm** [comment]
I have tested on DoTween 1.2.745 and Unity 2022.3.0f1, and its behaviour is like what you said that not allow to stop tweens inside Sequences.

In the following sample, when `t1.DoKill()` is called the animation doesn't stop. Only when `_seq.Kill()` is called then all animations are stoped.

There is no error when `t1.DoKill()` is called. I'm working on migrate DoTween to PrimeTween, and there are lot of legacy code that using this, so could you make `Tween.StopAll()` same as DoTween? Do not produce any errors, just ignore sequence. This should make the migration more fluently.

And I think the API `Sequence.Create(object sequenceTarget)` is good for me, I could fix the legacy animation easily with it.

```csharp
using DG.Tweening;
using UnityEngine;

public class Test1 : MonoBehaviour
{
    public Transform t1;
    public Transform t2;
    private Sequence _seq;
    private int _frame;

    void Start()
    {
        _seq = DOTween.Sequence();
        _seq.Insert(0, t1.DOMoveX(5, 0.1f));
        _seq.Insert(0, t2.DOMoveX(-5, 0.1f));
        _seq.SetLoops(-1);
    }

    void Update()
    {
        _frame++;
        if (_frame == 120)
        {
            t1.DOKill();
            Debug.Log("Kill t1");
        }

        if (_frame == 1200)
        {
            _seq.Kill();
            Debug.Log("Kill seq");
        }
    }
}
```

**Comment by networm** [comment]
> While I can make sure such a scenario doesn't produce any errors, I believe the proper fix should go much deeper than that.

When will this issue be fixed? Need to confirm an approximate time. There are some compatibility check works for migration.

**Comment by KyryloKuzyk** [comment]
> When will this issue be fixed? Need to confirm an approximate time. There are some compatibility check works for migration.

I hope it will happen early next week. I'm currently working on a big update that will bring new features, and this update will fix the issue by not allowing to stop tweens inside sequences. I'll keep you posted.

**Comment by KyryloKuzyk** [comment]
@networm I fixed the issue in version 1.1.0. Now PrimeTween doesn't allow to manipulate tweens inside Sequences and will log a warning to the console.

> could you make `Tween.StopAll()` same as DoTween?

Unfortunately, I can't change how things worked before in PrimeTween because it will break the code for old PrimeTween users. In PrimeTween, the Sequence is built on top of Tween: they use the same pool as tweens when you call Tween.SetTweensCapacity(), and they appear in the same debugging list when you observe the [PrimeTweenManager's](https://github.com/KyryloKuzyk/PrimeTween#debugging-tweens) inspector. The Tween.StopAll() method is designed to stop all animations, so it's reasonable that it should both tweens and sequences.

> And I think the API `Sequence.Create(object sequenceTarget)` is good for me, I could fix the legacy animation easily with it.

I will think more on this one. Here are my current concerns:
> // To support stopping sequences by target, I can add new API 'Sequence.Create(object sequenceTarget)'.
> // But 'sequenceTarget' is a different concept to tween's target, so I should not mix these two concepts together:
> //     'sequenceTarget' serves the purpose of unique 'id', while tween's target is the animated object.
> // In my opinion, the benefits of this new API don't outweigh the added complexity. A much more simpler approach is to store the Sequence reference and call sequence.Stop() directly.

**Comment by networm** [comment]
> Unfortunately, I can't change how things worked before in PrimeTween because it will break the code for old PrimeTween users.

I think you should think about DoTween migrating users, they need seamless migration. Without this `Tween.StopAll` no error warranty, migration is not done. There is a timebomb in code, and it will bomb one day in production cause there is a game logic called `Tween.StopAll` on a Sequence child Tween target. No one could guarantee that there is no such scenario cause it's runtime logic.

There is a script define `PRIME_TWEEN_DOTWEEN_ADAPTER`, `Tween.StopAll` could do nothing and have no errors when this is defined.

So without this compatibility, I think I should stop migration to PrimeTween and go back to DoTween.

Just guarantee the following code runs without errors:

```csharp
﻿using PrimeTween;
using UnityEngine;

public class Test1 : MonoBehaviour
{
    private int _frame;

    void Start()
    {
        var seq = Sequence.Create();
        seq.Group(Tween.LocalPositionX(transform, 0.6f, 0.1f));
        seq.SetCycles(10);
    }

    void Update()
    {
        _frame++;
        if (_frame == 120)
        {
            Tween.StopAll(transform);
        }
    }
}
```

> A much more simpler approach is to store the Sequence reference and call sequence.Stop() directly.

I think it's a better idea. `Sequence.Create(object sequenceTarget)` this is redundant.

**Comment by networm** [comment]
Thanks for detailed explanations. I have confused `DOTween.Kill(transform)` and `Tween.StopAll(transform)`, now I know it's different API for DoTween adapter and PrimeTween.
I will give feedback after trying it in project.

**Comment by KyryloKuzyk** [comment]
Great!
Please feel free to re-open the issue if you'll have any additional feedback.
