### ISSUE TITLE
The looping functionality within the Tween seems not working.

### ISSUE THREAD

**Issue by 0xdw** [KyryloKuzyk/PrimeTween#24]
I tried replacing the DOTween statement with PrimeTween, but instead of continuously scaling up and down, it just stops at the final number.

```c#
// DOTween
transform.DOScale(1.1f, 0.25f).SetLoops(-1, LoopType.Yoyo);

// PrimeTween
Tween.Scale(transform, 1.0f, 1.1f, 0.25f, Ease.Linear, -1, CycleMode.Yoyo);
```

**Comment by KyryloKuzyk** [comment]
Unfortunately, I wasn't able to reproduce the issue either with the latest version 1.0.17, or with the previous ones. Could you please tell me what version you are using? You can find it in the Package Manager or in the 'Packages/PrimeTween/package.json' file.

Could you please also try to debug this infinite tween with the [PrimeTweenManager's](https://github.com/KyryloKuzyk/PrimeTween#debugging-tweens) Inspector? Is there a change you stop the tween somewhere else in your code?

**Comment by 0xdw** [comment]
Yes, this is strange. Its not working on one of the positions. But it works fine in other positions. I'm not sure what causes this issue. But when it not works, I use a sequence of tweens with -1 cycles.

**Comment by networm** [comment]
Try to make a minimal reproduce project may be a good idea. Like what I submited in #23 [networm/TestPrimeTween1.0.17](https://github.com/networm/TestPrimeTween1.0.17)

**Comment by 0xdw** [comment]
Unfortunately, I cannot reproduce the issue on a new demo project with the same setup. But this is still my current project, which I cannot share. Let's close this for now, and I'll let you know if I can find a way to reproduce it.

**Comment by KyryloKuzyk** [comment]
Please feel free to re-open the issue if you have more details.
