### ISSUE TITLE
Unity 2022.3.17f1 last update

### ISSUE THREAD

**Issue by Peakaso** [KyryloKuzyk/PrimeTween#40]
For some unknown reason latest version [1.1.11] from the assetstore ist not working for me in this mentioned version of Unity.

What I did:
Updated package - everything went red Tween and Ease could not be found. I checked and compared files everything was as it should be so I tried another experiment.

I created fresh project and imported new version - not working.
Imported old version (one below) - working.

I dont mind this as the older version is without bugs for me its just seems really weird. Any ide what could be the reason?

Edit: Im using PrimeTween for months now so this is not my first update rodeo :D

**Comment by KyryloKuzyk** [comment]
Hmm, I'm also using this Unity version, but I can't reproduce the issue on my side. Can you please share the error you're getting?

Also, please check that PrimeTween is present in the Packages folder. If it's not, press the Assets/Plugins/PrimeTween/PrimeTweenInstaller/Install button.

And what's the previous version that works for you?

**Comment by Peakaso** [comment]
I had it installed so tried unninstall and install again - weird but problem solved :D thank you

**Comment by KyryloKuzyk** [comment]
Please reopen the issue if you’ll have more details.
