### ISSUE TITLE
Tweens do not have a fixedUpdate update mode? 

### ISSUE THREAD

**Issue by coty-crg** [KyryloKuzyk/PrimeTween#57]
I see you have an "useUnscaledTime" parameter, but there's no "useFixedTime" parameter. I'm currently trying out the plugin to replace DoTween, but we use fixed update tweens quite often.

**Comment by coty-crg** [comment]
Ah nevermind, the API is just confusing for it. It's hidden inside of TweenSettings but not available in the methods settings parameters.

**Comment by KyryloKuzyk** [comment]
Fixed update tweens should be used very rare, so this feature is hidden inside TweenSettings to make the API cleaner. 

Can you please share where you use fixed update tweens? In the majority of cases fixed update tweens can be replaced with a regular ones. Currently, this is the only use case I’ve encountered that truly requires fixed update: https://forum.unity.com/threads/primetween-high-performance-animations-and-sequences.1479609/page-3#post-9457943

**Comment by coty-crg** [comment]
Hey. Our player controller and NPC AI all runs on FixedUpdate (it makes doing stuff like networking and replays easier). Because of that, our tweens related to those things also run on FixedUpdate. If they do not, things like rigidbody interpolation do not work properly.
