### ISSUE TITLE
Ask for review only in response to user’s action. 

### ISSUE THREAD

**Issue by coty-crg** [KyryloKuzyk/PrimeTween#58]
![image](https://github.com/KyryloKuzyk/PrimeTween/assets/3958573/e2d93a5b-3c43-44c6-8a09-2b5c438dc1c3)

I moved the package to be an embedded one and removed the code entirely, for reference to anyone else who finds this. 

![image](https://github.com/KyryloKuzyk/PrimeTween/assets/3958573/ab38a80e-b3ca-4d57-8f8a-b35de1c7d9d6)

**Comment by KyryloKuzyk** [comment]
Thanks for sharing! 

The review request happens only once and only in response to the user’s action (updating PrimeTween to a newer version). 

I made this request to be as non-intrusive as possible. And if you saw it one, you’ll never see it again on this machine. PrimeTween is completely free, and this review request helps other users to discover it.

**Comment by coty-crg** [comment]
The problem is it's once per machine. I installed it on one machine, then another team member opened the project and got the pop up. 

Also, the label "hide forever" is misleading, because if one team member updates it all members will also get this pop up.

**Comment by KyryloKuzyk** [comment]
Yeah, I didn’t account for the case when one team member updates the plugin. In this case, other team members will receive the request without the user action. 

I’ll think about making the request only in response to pressing the ‘update’ button or saving the “never ask again” project-wise.

**Comment by coty-crg** [comment]
Thanks! By the way, in my own asset store plugins, I use a ScriptableObject for stuff like this. Source control will track changes to it, and its easily editable by users directly if they really want to.

**Comment by KyryloKuzyk** [comment]
I fixed this in version 1.1.15. Now PrimeTween only asks for review after the user updates the plugin in the Package Manager.
Other team members will not see the review request after they pull changes from the repo.

Huge thanks for reporting this!
