### ISSUE TITLE
Equivalent of Ease.Flash

### ISSUE THREAD

**Issue by meturgut** [KyryloKuzyk/PrimeTween#59]
Hi @KyryloKuzyk ,
What is the equivalent of "Ease.Flash (Ease.OutFlash, Ease.InFlash)" in the Dotween library?

**Comment by KyryloKuzyk** [comment]
Hey @meturgut 

Can you please provide a usage example? I'm currently trying to understand how to properly use the Ease.Flash, and it seems like the same as using multiple cycles on a tween. These two animations produce visually the same results, for example:
```csharp
// DOTween:
transform.DOMove(new Vector3(0, 5), 1f).SetEase(Ease.InFlash, overshoot: 5);
// PrimeTween:
Tween.Position(transform, new Vector3(0, 5), 1f / 5f, Ease.InSine, cycles: 5, cycleMode: CycleMode.Rewind);
```

Are there any differences between Ease.Flash and using multiple animation cycles?

**Comment by meturgut** [comment]
I want to convert code previously written using DoTween to PrimeTween. (Only move functions used) The example you created using "Ease.InFlash" is not exactly the same animation, but it is quite similar. 

What are the equivalents of "OutFlash" and "InOutFlash"?

 `
block.transform.DOMove(targetPos, duration).SetEase(Ease.OutFlash);
block.transform.DOMove(targetPos, duration).SetEase(Ease.InOutFlash);

`

**Comment by KyryloKuzyk** [comment]
> What are the equivalents of "OutFlash" and "InOutFlash"?

You've probably figured it out by yourself, but this should be similar to the Ease.InFlash equivalent you provided, but with OutQuad and InOutQuad eases:
```csharp
Tween.Position(transform, new Vector3(0, 5), 1f / 5f, Ease.OutQuad, cycles: 5, cycleMode: CycleMode.Rewind);
Tween.Position(transform, new Vector3(0, 5), 1f / 5f, Ease.InOutQuad, cycles: 5, cycleMode: CycleMode.Rewind);
```
