### ISSUE TITLE
GetTweensCount broken for sequences

### ISSUE THREAD

**Issue by sinap-se** [KyryloKuzyk/PrimeTween#60]
Hello,

I am trying to use Tween.GetTweensCount(transform) to determine if an object is being animated without having access to the Tween/Sequence involved. However, what happens is that processAll_internal asserts so I never get a non-zero value back.

My expectation is that I would get N tweens back where N is the number of tweens involved even if they are part of a sequence.

Please let me know if I am missing something.

Thanks!

**Comment by KyryloKuzyk** [comment]
Thanks for reporting the issue!
Can you please provide the assertion stack trace by copy-pasting it here?

**Comment by sinap-se** [comment]
I worked around the issue so I can no longer generate it. However, the issue is on line 384 in the processAll_internal method in the PrimeTweenManager. Since the GetTweensCount uses the processAll method despite being a read-only exercise, the tween.IsInSequence() guard prevents the method from working as I would expect in Sequences.

**Comment by KyryloKuzyk** [comment]
Thanks! It seems like the isInSequence() guard is not needed in this case. 
Can you please tell how did you work around the issue?

**Comment by sinap-se** [comment]
It isn't needed in this case because the predicate doesn't alter the Tween but the method does have the ability to mess with things. There probably needs to be another read-only, non-predicate path for these sorts of informational cases.

As for the work around, I chose to cache the last invoked Tween and test to see if it's alive or not. I think I end up missing cases where one tween is longer than another as I have noted that sometimes if I am overwriting tweens quickly a longer initial tween will end up completing after being overwritten by a shorter tween but I have yet to observe a problem.

**Comment by KyryloKuzyk** [comment]
I fixed this in version 1.1.15.

But now I'm thinking that adding the Tween.GetTweensCount(target) API was a mistake. This method has an O(n) complexity, meaning that it iterates all current tweens, which goes against the high-performance philosophy of the library. 

A more performant and more obvious approach is storing the tween/sequence to a field and checking the `isAlive` property, as you did in your workaround. I should probably deprecate this method in future releases, along with StopAll/CompleteAll/SetPausedAll() methods that accept the target parameter and leave only the targetless versions.

Huge thanks for reporting the bug!
