### ISSUE TITLE
Redundant error message log spam when using useFixedUpdate on both a Sequence and its Tweens 

### ISSUE THREAD

**Issue by coty-crg** [KyryloKuzyk/PrimeTween#66]
Here is some example code. The sequence has useFixedUpdate, and the Tween also has useFixedUpdate. 
![image](https://github.com/KyryloKuzyk/PrimeTween/assets/3958573/7b9a1cde-e334-49a6-ab9b-1c492586d525)

This results in the following error log: 

`'useFixedUpdate' was ignored after adding tween/sequence to the Sequence. Parent Sequence controls isPaused/timeScale/useUnscaledTime/useFixedUpdate of all its children tweens and sequences.`

It shouldn't log when I'm intentionally using fixed update?

**Comment by KyryloKuzyk** [comment]
Hi, thanks for reporting this!
I’m aware of this and will it soon. https://github.com/KyryloKuzyk/PrimeTween/discussions/61

**Comment by KyryloKuzyk** [comment]
I fixed the issue in version 1.1.16.
Now PrimeTween only logs an error when sequence.useFixedUpdate != childTween.useFixedUpdate. So in your case, the error should be gone. Can you please update and confirm it?
