### ISSUE TITLE
[Feature Request] Expose access to `StandardEasing.Evaluate` 

### ISSUE THREAD

**Issue by noio** [KyryloKuzyk/PrimeTween#75]
Sometimes I'm doing some manual easing, and it would be great if I could recycle the ease functions from PrimeTween (instead of having to copy or install another library with the same easing functions)

I.e. if I could call `var progress = StandardEasing.Evaluate(t, Ease.InOutQuad)` and use the results in my code.

**Comment by KyryloKuzyk** [comment]
Hey! This feature is available, but it’s currently experimental. Please see this answer: https://forum.unity.com/posts/9644069/

Can you please show an example where you need this feature?

**Comment by KyryloKuzyk** [comment]
Huge thanks for kind words!

> But actually in this case I've just replaced it with running a Tween.Custom() in parallel, which works fine too.

Yeah, exactly my thoughts. In the majority of cases, Tween.Custom() can be used instead of Easing.Evaluate(). This is the reason why Easing.Evaluate() is currently experimental.
