### ISSUE TITLE
async await GC

### ISSUE THREAD

**Issue by b4lie** [KyryloKuzyk/PrimeTween#77]
I saw in the document that async await will result in GC allocation, so you recommend using sequences. But have you ever considered supporting unitask extensions

**Comment by KyryloKuzyk** [comment]
PrimeTween already can work together with UniTask: you can `await` tweens and sequences like async methods, so all UniTask features that work with async methods also work with PrimeTween's tweens and sequences with 0GC.

Do you have any specific use cases where PrimeTween can be closely integrated with UniTask?
