### ISSUE TITLE
PrimeTween Demo doesn't work with the New Input System

### ISSUE THREAD

**Issue by yosun** [KyryloKuzyk/PrimeTween#85]
Just grabbed PrimeTween... in a live project to replace DotTween Pro... It's not compatible with New Input System? 

InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.
UnityEngine.Input.GetButtonDown (System.String buttonName) (at /Users/bokken/build/output/unity/unity/Modules/InputLegacy/Input.bindings.cs:373)
UnityEngine.EventSystems.BaseInput.GetButtonDown (System.String buttonName) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/InputModules/BaseInput.cs:126)
UnityEngine.EventSystems.StandaloneInputModule.ShouldActivateModule () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/InputModules/StandaloneInputModule.cs:229)
UnityEngine.EventSystems.EventSystem.Update () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:503)

**Comment by KyryloKuzyk** [comment]
Hi!

PrimeTween is compatible with the New Input System, but I'm afraid I made the Demo only with the Legacy input system in mind. 

I'll see if I can upgrade the Demo to work with both input systems. Thanks for bringing attention to the issue!

**Comment by KyryloKuzyk** [comment]
Fixed in version 1.1.20. Huge thanks for reporting the issue!
