### ISSUE TITLE
OnStart callback with Sequence.Group()

### ISSUE THREAD

**Issue by meturgut** [KyryloKuzyk/PrimeTween#96]
Hello @KyryloKuzyk,

`Sequence.Create().ChainCallback(() => transform.localScale = Vector3.zero).Group(Tween.Scale(transform, 1, 1));`

Is it possible to call a callback  before Sequence.Group() runs?

**Comment by meturgut** [comment]
I found it. 

`Sequence.Create().Group(Tween.Scale(transform, 0, 1, 1));`

**Comment by KyryloKuzyk** [comment]
> Is it possible to call a callback before Sequence.Group() runs?

I'm sorry for the late reply. Your original code sample is correct and achieves this goal.
More info: https://github.com/KyryloKuzyk/PrimeTween/discussions/90#discussioncomment-10365775
